Debug/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from requestapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.RequestListView.as_view(), name='home'),
    path('users/', include('userapp.urls')),
    path('requests/', include('requestapp.urls')),
    path('settings/',include('settingapp.urls')),
    path('profile/', include('profileapp.urls')),
    path('hunters/', include('hunterapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hunterapp/urls.py
from django.urls import path

from hunterapp import views
from hunterapp.views import *

app_name = "hunterapp"

urlpatterns = [
    path('create/', HunterCreateView.as_view(), name='create'),
    path('list/', HunterListView.as_view(), name='list'),
    path('detail/<int:pk>', HunterDetailView.as_view(), name='detail'),
    path('update/<int:pk>', HunterUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.hunter_delete, name='delete'),
]

requestapp/urls.py
from django.urls import path

from requestapp import views
from requestapp.views import RequestUpdateView, RequestListView, RequestCreateView, RequestDetailView

app_name = "requestapp"

urlpatterns = [
    path('create/', RequestCreateView.as_view(), name='create'),
    path('list/', RequestListView.as_view(), name='list'),
    path('detail/<int:pk>', RequestDetailView.as_view(), name='detail'),
    path('update/<int:pk>', RequestUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.request_delete, name='delete'),
]

hunterapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.timezone import now
from pytz import timezone
from Debug import settings


class Hunter(models.Model):
    title = models.CharField(max_length=50, null=False)
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='hunter', null=True)
    created_at = models.DateTimeField(default=now, editable=False)

    @property
    def created_at_korean_time(self):
        korean_timezone = timezone(settings.TIME_ZONE)
        return self.created_at.astimezone(korean_timezone)
    content = models.TextField(null=True)
    location = models.CharField(max_length=200, null=False)

    def __str__(self):
        return self.title

hunterapp/forms.py
from django.forms import ModelForm
from django import forms

from hunterapp.models import Hunter


class HunterCreationForm(ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'editable text-left',
                                                           'style': 'height: auto;'}))

    class Meta:
        model = Hunter
        fields = ['title', 'location', 'content']

hunterapp/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, DetailView, UpdateView

from hunterapp.decorators import request_ownership_required
from hunterapp.forms import HunterCreationForm
from hunterapp.models import Hunter


class HunterListView(ListView):
    model = Hunter
    context_object_name = 'hunter_list'
    template_name = 'hunterapp/list.html'
    paginate_by = 8


@method_decorator(login_required(login_url=reverse_lazy('userapp:login')), 'get')
@method_decorator(login_required(login_url=reverse_lazy('userapp:login')), 'post')
class HunterCreateView(CreateView):
    model = Hunter
    context_object_name = 'target_hunter'
    form_class = HunterCreationForm
    template_name = 'hunterapp/create.html'

    def form_valid(self, form):
        temp_article = form.save(commit=False)
        temp_article.writer = self.request.user
        temp_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('hunterapp:detail', kwargs={'pk': self.object.pk})


class HunterDetailView(DetailView):
    model = Hunter
    context_object_name = 'target_hunter'
    template_name = 'hunterapp/detail.html'


@method_decorator(login_required(login_url=reverse_lazy('userapp:login')), 'get')
@method_decorator(login_required(login_url=reverse_lazy('userapp:login')), 'post')
@method_decorator(request_ownership_required, 'get')
@method_decorator(request_ownership_required, 'post')
class HunterUpdateView(UpdateView):
    model = Hunter
    context_object_name = 'target_hunter'
    form_class = HunterCreationForm
    template_name = 'hunterapp/update.html'

    def get_success_url(self):
        return reverse('hunterapp:detail', kwargs={'pk': self.object.pk})


@login_required(login_url='/users/login/')
@request_ownership_required
def hunter_delete(request, pk):
    quest = Hunter.objects.get(pk=pk)
    if quest.writer == request.user:
        quest.delete()
        return HttpResponseRedirect(reverse('home'))

hunterapp/templates/hunterapp/create.html
{% extends 'base.html' %}

{% block content %}
    <div class="center">
        <div class="content">
            <h4>헌터 등록하기</h4>
            <hr>
            <form action="{% url 'hunterapp:create' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table style="margin: 0 auto;">
                    {{form.as_table}}
                </table>
                <button type="submit" class="material-icons">add</button>
                <button type="button" class="material-icons">cancel</button>
            </form>
        </div>
    </div>

{% endblock %}

hunterapp/templates/hunterapp/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="center">
    <h2>{{ target_hunter.title }}</h2>
    <a href="#">{{ target_hunter.writer }}</a> | {{ target_hunter.created_at }}

    <div class="menu">
        <div class="info"><a href="{% url 'hunterapp:update' pk=target_hunter.pk %}">수정 </a><a href="{% url 'hunterapp:delete' pk=target_hunter.pk %}"> 삭제 </a></div>
    </div>

    <hr>

    <div class="content">{{ target_hunter.content }}</div>
    <div class="content">
        <a href="#" class="button">의뢰하기</a>
    </div>

</div>

{% endblock %}

hunterapp/templates/hunterapp/list.html
{% extends 'base.html' %}

{% block content %}

<div class="content center">
    {% if hunter_list %}
        <div class="container">
            {% for hunter in hunter_list %}
                <div class="box">
                    <a href="{% url 'hunterapp:detail' pk=hunter.pk %}">{{ hunter.title }}</a>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <span class="logo">👀 조치원의 벌레 헌터를 찾고 있어요! 👀</span>
    {% endif %}
    <div class="content">
        <a class="button add" href="{% url 'hunterapp:create' %}">헌터 등록하기</a>
    </div>

</div>
{% endblock %}

hunterapp/templates/hunterapp/update.html
{% extends 'base.html' %}
{% block content %}

    <div class="center">
        <div>
            <h4>도움 글 수정하기</h4>
            <hr>
            <form action="{% url 'requestapp:update' pk=target_request.pk %}" method="post" class="form-inline">
                {% csrf_token %}
                <table>
                    {{form.as_table}}
                </table>
                <button type="submit" class="material-icons">confirm</button>
                <button type="button" class="material-icons">cancel</button>
            </form>
        </div>
    </div>

{% endblock %}