Debug/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from requestapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.RequestListView.as_view(), name='home'),
    path('users/', include('userapp.urls')),
    path('requests/', include('requestapp.urls')),
    path('settings/',include('settingapp.urls')),
    path('profile/', include('profileapp.urls')),
    path('hunters/', include('hunterapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hunterapp/urls.py
from django.urls import path

from hunterapp import views
from hunterapp.views import *

app_name = "hunterapp"

urlpatterns = [
    path('create/', HunterCreateView.as_view(), name='create'),
    path('list/', HunterListView.as_view(), name='list'),
    path('detail/<int:pk>', HunterDetailView.as_view(), name='detail'),
    path('update/<int:pk>', HunterUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.hunter_delete, name='delete'),
]

requestapp/urls.py
from django.urls import path

from requestapp import views
from requestapp.views import RequestUpdateView, RequestListView, RequestCreateView, RequestDetailView

app_name = "requestapp"

urlpatterns = [
    path('create/', RequestCreateView.as_view(), name='create'),
    path('list/', RequestListView.as_view(), name='list'),
    path('detail/<int:pk>', RequestDetailView.as_view(), name='detail'),
    path('update/<int:pk>', RequestUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.request_delete, name='delete'),
]

settingapp/urls.py
from django.urls import path

from settingapp.views import option

app_name = "settingapp"

urlpatterns = [
    path('', option, name='option'),

]

userapp/urls.py
from django.urls import path
from userapp.views import *

from userapp.views import UserCreateView

app_name = "userapp"

urlpatterns = [
    path('login/', login_check, name='login'),
    path('logout/', logout, name="logout"),
    path('signup/', signup, name="signup")
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% include 'head.html' %}
<body>
    {% include 'header.html' %}

    {% block content %}
    {% endblock %}

    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
<footer>
    <hr>
    <div class="center">2021 마피아 해커톤 | 조치원 해충 박멸 프로젝트</div>
    <h6 class="center logo">이지원  김태호  조빈경</h6>
</footer>

templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Debug</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- default style sheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css'%}">

    <!-- material icons -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">

    <!-- bootstrap link -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <!--  DEFAULT CSS LINK  -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>

templates/header.html
<header class="header">
    <a href="{% url 'home' %}"><h1 class="logo"><span class="material-icons logo" style="font-size:4rem;">bug_report</span>Debug</h1></a>

    <div>
        <a href="{% url 'hunterapp:list' %}">헌터</a>
        <a href="{% url 'requestapp:list' %}">의뢰인</a>
    </div>


    <div style="top: 40px; right: 80px; position: absolute;">
        {% if not user.is_authenticated %}
      <a href="{% url 'userapp:login' %}?next={{ request.path }}">
        <span>login</span>
      </a>
      <a href="{% url 'userapp:signup' %}">
        <span>SignUp</span>
      </a>
      {% else %}
        <span>MyPage</span>
      <a href="{% url 'userapp:logout' %}?next={{ request.path }}">
        <span>logout</span>
      </a>
      {% endif %}
    </div>
    <div style="top: 5px; right: 30px; position: absolute;">
    <a href="{% url 'settingapp:option' %}" style=""><h1 class="setting_logo"><span
            class="material-icons setting_logo" style="font-size:4rem;">settings</span></h1></a>
    </div>

</header>
<hr>