Debug/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from requestapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.RequestListView.as_view(), name='home'),
    path('users/', include('userapp.urls')),
    path('requests/', include('requestapp.urls')),
    path('settings/',include('settingapp.urls')),
    path('profile/', include('profileapp.urls')),
    path('hunters/', include('hunterapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

requestapp/urls.py
from django.urls import path

from requestapp import views
from requestapp.views import RequestUpdateView, RequestListView, RequestCreateView, RequestDetailView

app_name = "requestapp"

urlpatterns = [
    path('create/', RequestCreateView.as_view(), name='create'),
    path('list/', RequestListView.as_view(), name='list'),
    path('detail/<int:pk>', RequestDetailView.as_view(), name='detail'),
    path('update/<int:pk>', RequestUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.request_delete, name='delete'),
]

requestapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.timezone import now
from pytz import timezone
from Debug import settings


class Quest(models.Model):
    title = models.CharField(max_length=50, null=False)
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='request', null=True)
    created_at = models.DateTimeField(default=now, editable=False)

    @property
    def created_at_korean_time(self):
        korean_timezone = timezone(settings.TIME_ZONE)
        return self.created_at.astimezone(korean_timezone)

    img = models.ImageField(upload_to='request/', null=True)
    content = models.TextField(null=True)
    location = models.CharField(max_length=200, null=False)

    start_price = models.IntegerField(default=1)
    end_price = models.IntegerField(default=1)
    is_completed = models.BooleanField(default=False)

    def __str__(self):
        return self.title

requestapp/forms.py
from django.forms import ModelForm
from django import forms

from requestapp.models import Quest


class QuestCreationForm(ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'editable text-left',
                                                           'style': 'height: auto;'}))

    class Meta:
        model = Quest
        fields = ['title', 'img', 'location', 'start_price', 'end_price', 'content']

requestapp/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from requestapp.decorators import request_ownership_required
from requestapp.forms import QuestCreationForm
from requestapp.models import Quest


class RequestListView(ListView):
    model = Quest
    context_object_name = 'request_list'
    template_name = 'requestapp/list.html'
    paginate_by = 8


@method_decorator(login_required(login_url=reverse_lazy('userapp:login')), 'get')
@method_decorator(login_required(login_url=reverse_lazy('userapp:login')), 'post')
class RequestCreateView(CreateView):
    model = Quest
    context_object_name = 'target_request'
    form_class = QuestCreationForm
    template_name = 'requestapp/create.html'

    def form_valid(self, form):
        temp_article = form.save(commit=False)
        temp_article.writer = self.request.user
        temp_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('requestapp:detail', kwargs={'pk': self.object.pk})


class RequestDetailView(DetailView):
    model = Quest
    context_object_name = 'target_request'
    template_name = 'requestapp/detail.html'


@method_decorator(login_required(login_url=reverse_lazy('userapp:login')), 'get')
@method_decorator(login_required(login_url=reverse_lazy('userapp:login')), 'post')
@method_decorator(request_ownership_required, 'get')
@method_decorator(request_ownership_required, 'post')
class RequestUpdateView(UpdateView):
    model = Quest
    context_object_name = 'target_request'
    form_class = QuestCreationForm
    template_name = 'requestapp/update.html'

    def get_success_url(self):
        return reverse('requestapp:detail', kwargs={'pk': self.object.pk})


@login_required(login_url='/users/login/')
@request_ownership_required
def request_delete(request, pk):
    quest = Quest.objects.get(pk=pk)
    if quest.writer == request.user:
        quest.delete()
        return HttpResponseRedirect(reverse('home'))

requestapp/templates/requestapp/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<div class="center">
    <h2>{{ target_request.title }}</h2>
    <a href="#">{{ target_request.writer }}</a> | {{ target_request.created_at }}

    <div class="flex_box">
        <div>
            <span class="info">위치 | {{ target_request.location }}</span>
            <span class="info">가격 | {{ target_request.start_price }} - {{ target_request.end_price }} 원</span>
        </div>
        <div class="menu">
            <div class="info"><a href="{% url 'requestapp:update' pk=target_request.pk %}">수정 </a><a href="{% url 'requestapp:delete' pk=target_request.pk %}"> 삭제 </a></div>
        </div>
    </div>

    <hr>

    <div class="content">{{ target_request.content }}</div>
    <img src="{{ target_request.img.url }}" alt="{{ target_request.title }}" style="width: 80%; border-radius: 1rem; margin: 2rem 0;">
    <div class="content">
        <a href="#" class="button">의뢰 수락하기</a>
    </div>

</div>

{% endblock %}

requestapp/templates/requestapp/list.html
{% extends 'base.html' %}

{% block content %}

<div class="content center">
    {% if request_list %}
        <div class="container">
            {% for request in request_list %}
                <div class="box">
                    <a href="{% url 'requestapp:detail' pk=request.pk %}">{{ request.title }}</a>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <span class="logo">🐛 어라... 조치원의 벌레가 멸종된 걸까요? &nbsp;🐛</span>
    {% endif %}
    <div class="content">
        <a class="button add" href="{% url 'requestapp:create' %}">도움 요청하기</a>
    </div>

</div>
{% endblock %}